### ISSUE TITLE
Podfile添加sdk库，完成后提示'SDWebImage/SDWebImage.h' file not found

### ISSUE THREAD

**Issue by DonsonWu** [GoBelieveIO/im_ios#11]
Podfile添加sdk库，完成后提示'SDWebImage/SDWebImage.h' file not found
![image](https://user-images.githubusercontent.com/15194024/69412189-5ea70800-0d49-11ea-894c-bbcf52ac63e1.png)

**Comment by richmonkey** [comment]
重新pod install下， sdwebimage依赖的版本出问题了
