### ISSUE TITLE
Can you change UIWebView to WKWebView

### ISSUE THREAD

**Issue by shen666** [GoBelieveIO/im_ios#13]
Can you change UIWebView to WKWebView? The app that contains UIWebView can't upload to the AppStore now.

**Comment by richmonkey** [comment]
no any uiwebview or wkwebview in the project

**Comment by shen666** [comment]
<img width="500" alt="截屏2020-09-19下午11 37 15" src="https://user-images.githubusercontent.com/22339405/93671011-19bb4180-fad2-11ea-9ece-82ac232f2692.png">

**Comment by richmonkey** [comment]
fix now.
