### ISSUE TITLE
TextMessageViewController

### ISSUE THREAD

**Issue by tanhuang** [GoBelieveIO/im_ios#17]
#import <gobelieve/TextMessageViewController.h>

找不到头文件

demo中也没有。。

**Comment by richmonkey** [comment]
已经被删除了

**Comment by tanhuang** [comment]
@interface RoomViewController : TextMessageViewController
那聊天室继承了这个控制器，需要改成什么？

**Comment by richmonkey** [comment]
不要使用roomviewcontroller， 直接使用imService收发room消息

**Comment by tanhuang** [comment]
是这样，我想跑你们demo，看看功能，你说roomviewcontroller不用，那demo就不能用了哦。

**Comment by richmonkey** [comment]
你可以跑im_demo或者group_demo

**Comment by tanhuang** [comment]
嗯嗯。我想问下，测试的账号，可以随便输入的吗？
我用123456，获取不到token

**Comment by richmonkey** [comment]
用小一点的数字， 1000以内
