### ISSUE TITLE
OC 和 Swift 混编 出现错误

### ISSUE THREAD

**Issue by tanpengsccd** [GoBelieveIO/im_ios#4]
podfile 文件里
```
use_frameworks!
```
后 出现错误
![image](https://user-images.githubusercontent.com/13959880/30603108-1e531a5e-9d99-11e7-9cb6-2945840000bc.png)

**Comment by richmonkey** [comment]
fix:https://github.com/GoBelieveIO/im_ios/commit/793695fee3a37932ddccf3b563ffa95175756384

**Comment by tanpengsccd** [comment]
swift 混编 打包时 也会出现 error， 需要 关闭 这个 库的bitcode

**Comment by richmonkey** [comment]
Thanks https://github.com/GoBelieveIO/im_ios/commit/f97730aeb6b0c28a0c4fc13572f87c991ddc208b
