### ISSUE TITLE
遇到问题：退出程序或者删除程序，聊天记录全部清空

### ISSUE THREAD

**Issue by EveryStepOfTheWay** [GoBelieveIO/im_ios#8]
1.  操作的代码： 运行程序以im_ios的im_demo做测试
2.  遇到问题： 退出程序或者删除程序，聊天记录全部清空
3.  请解决：    目前测试的是单聊， 但是希望“客服和单聊”（im_demo和customer_demo）都可以解决这个问题。 因为之后我们会用到这两个。 如果这个问题不解决， 相当于客户和顾客的聊天记录是无法保存的， 那么相当于有纠纷的时候， 我们无法把聊天作为解决问题的资料。 
拿淘宝做演示，无论是退出程序再次打开， 还是删除程序再次安装，聊天记录都是存在的。 
4.  我们自己的努力部分：   我们自己做了测试，我们的服务器im_server搭建成功了，数据库和表单都存在，但是记录无法保存。考虑到server的原码是go语言， 请解决这个错误， 并且更新到github上面。 
谢谢。

**Comment by richmonkey** [comment]
聊天记录是保存在手机本地sqlite中的， 删除程序， 数据会连带着被清空的， 退出程序是要应用自己去管理db中的数据的。

**Comment by EveryStepOfTheWay** [comment]
贵公司能不能给公开的群里， 留一个人配合回答问题呢。 
现在所有问题的回复都是， 你去用融云吧， 你去用环信吧。 你别用了。 
这样的沟通是不是不太好。 




------------------ 原始邮件 ------------------
发件人: "侯学华"<notifications@github.com>;
发送时间: 2019年7月16日(星期二) 中午11:30
收件人: "GoBelieveIO/im_ios"<im_ios@noreply.github.com>;
抄送: "许宗惠"<157203155@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [GoBelieveIO/im_ios] 遇到问题：退出程序或者删除程序，聊天记录全部清空 (#8)




聊天记录是保存在手机本地sqlite中的， 删除程序， 数据会连带着被清空的， 退出程序是要应用自己去管理db中的数据的。
